### ISSUE TITLE
Monitoring/alerting for LVM disk usage

### ISSUE THREAD

**Issue by allenporter** [allenporter/k8s-gitops#151]
Today a lvm disk filled on one vm, and the vms all had io-errors. I believe this was because I previously ignored a warning about flex disks being allowed to grow beyond size of the physical disk.

Would be good to add monitoring and alerting for lvm disk usage.

**Comment by allenporter** [comment]
This was done using prometheus-pve-exporter in the private repo:

```
  - alert: PveDiskUsage
    expr: pve_disk_usage_bytes{id=~"storage/.*"} / pve_disk_size_bytes{id=~"storage/.*"} > 0.8
    for: 10m
    labels:
      severity: page
    annotations:
      summary: "pve storage 80% full {{ $labels.id }} on {{ $labels.instance }}."
      description: "Storage {{ $labels.instance }} is > 80% full on {{ $labels.instance}}."
```
