### ISSUE TITLE
teslamate grafana source needs to share a secret

### ISSUE THREAD

**Issue by allenporter** [allenporter/k8s-gitops#214]
Teslamate is configured to use a password as the secret. However, the grafana source right now a configmap with a plain text secret.  (it's not working, since its not using the same secret):

https://github.com/allenporter/k8s-gitops/blob/main/home/base/teslamate/grafana-datasource.yaml
```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource
  namespace: teslamate
  labels:
    grafana_datasource: "1"
data:
  ha-datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: TeslaMate
      type: postgres
      url: teslamate-postgresql.teslamate:5432
      database: teslamate
      user: teslamate
      password: teslamate
      access: proxy
      jsonData:
        sslmode: disable
        timeInterval: 30s
```

Next step is to figure out the simplest way to make a field of that config map pull in the secret.  One option is to make this whole thing a secret, but then it makes it harder to manage the rest of the contents in ha-datasource.yaml above.  Effectively, I want to have the ConfigMap code above in git, just without the secret, similar to a flux `HelmRelease` with `valuesFrom` a secret. (And then the whole contents of the config map above probably need to also be in a secret)
